version: "3.6"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:80
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - apis

  apis:
    build:
      context: ./apis
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./apis/.env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
    depends_on:
      - mongo
    links:
      - mongo
      - redis-master
      - redis-sentinel-0
      - redis-sentinel-1

  mongo:
    image: mongo
    ports:
      - 27017:27017

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:8000
    depends_on:
      - client
      - apis

  redis-master:
    build:
      context: ./redis-master
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 6379:6379

  redis-sentinel-0:
    build:
      context: ./redis-sentinel-0
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 26379:26379
    depends_on:
      - redis-master
    links:
      - redis-master

  redis-sentinel-1:
    build:
      context: ./redis-sentinel-1
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 26380:26380
    depends_on:
      - redis-master
    links:
      - redis-master
