version: '3.1'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:80
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - apis

  apis:
    build:
      context: ./apis
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./apis/.env
    environment:
      - NODE_ENV=production
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:8000
    depends_on:
      - client
      - apis
